[package]
name = "magicka-save-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
eyre = "0.6.8"
tap = "1.0.1"
thiserror = "1.0.37"
